GlobalPlanner:
  allow_unknown: true         # 允许全局规划器在未知区域规划
  default_tolerance: 0.05     # 默认的路径容忍度
  use_dijkstra: true          # 使用Dijkstra算法
  use_quadratic: true         # 使用二次插值
  use_grid_path: false        # 使用梯度路径而不是网格路径
  outline_map: true           # 给地图边界加一圈代价，避免贴边规划
  old_navfn_behavior: false

  publish_potential: false    

  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3.0

  orientation_mode: 1
  orientation_window_size: 1
